version: '3.1'

services:
  af-opt:
    build: .
    environment:
      - SMTP_SETTINGS=/run/secrets/smtp_settings.cfg
      - RESULTS_DIR=results
    volumes:
      - ./filenames.cfg:/af-opt/filenames.cfg
      - ./Runfile:/af-opt/Runfile
      - ./results/:/af-opt/results
    secrets:
      - smtp_settings.cfg

secrets:
  smtp_settings.cfg:
    file: smtp_settings.cfg